### PR TITLE
Feat: fzf

### PR DESCRIPTION
**Pull request by justfoolingaround**

### CODE REVIEW

**Comment by justchokingaround** [comment]
yor :/

**Comment by mrfluffy-dev** [comment]
I fall in to a endless loop if I 

1. select an image 
2. click "persist selection for next in queue"
3. click preview

**Comment by mrfluffy-dev** [comment]
Also is it even possible to go to the next image on the list without needing to go back to the main menu and re scrolling all the way down.

FYI it looks amazing.

**Comment by justfoolingaround** [comment]
Resolved by removing preview for persist mode as that does not seem like a viable use-case.

**Comment by mrfluffy-dev** [comment]
> Resolved by removing preview for persist mode as that does not seem like a viable use-case.

Cool thanks. that makes more sense yes.

**Comment by justfoolingaround** [comment]
> Also is it even possible to go to the next image on the list without needing to go back to the main menu and re scrolling all the way down.

Sadly, I don't think this would be possible without sending user key inputs to `fzf` externally.

**Comment by mrfluffy-dev** [comment]
is there a keybinding I am missing that can be used to do that (So I can add it to the documentation)

**Comment by justfoolingaround** [comment]
I don't think so, by externally, I mean by creating a child subprocess that would then set `fzf` as an active process and then, send keyboard inputs to go to the previous index. 

This is just a theoretical idea. Don't worry about it.

**Comment by mrfluffy-dev** [comment]
coz it is possible to go strait to the main menu by pressing escape so it should be possible. (in my uneducated in fzf opinion)

**Comment by justfoolingaround** [comment]
> coz it is possible to go strait to the main menu by pressing escape so it should be possible. (in my uneducated in fzf opinion)

This more of the program ignoring and taking you back to the main screen because you didn't give it an appropriate option. It is impossible to load `fzf` from a cached state. The `fzf` calls retain the previous images because that algorithm is executed unknown to the user in this code itself.

**Comment by mrfluffy-dev** [comment]
big sad indeed. well it is not bad I would have liked a next and previous option when you are on an image.
but if it cant be helped it cant be helped. for now I am happy to accept the pull.

**Comment by justfoolingaround** [comment]
Thank you.

**Pull request merged**
